language: node_js
node_js:
  - 12
services:
  - docker
# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed anhnm123/udagram-api-feed:v4
  - docker tag udagram-api-user anhnm123/udagram-api-user:v4
  - docker tag udagram-frontend anhnm123/udagram-frontend:v4
  - docker tag reverseproxy anhnm123/reverseproxy:v4
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push
  - docker push anhnm123/udagram-api-feed:v4
  - docker push anhnm123/udagram-api-user:v4
  - docker push anhnm123/udagram-frontend:v4
  - docker push anhnm123/reverseproxy:v4
